version: '3.9'
services:
  db:
    mem_limit: 128m
    image: postgres:latest
    container_name: minitwit-db
    env_file:
      - .secrets
    healthcheck:
      #This command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  minitwit-api:
    mem_limit: 512m
    build:
      context: .
      dockerfile: ./src/minitwit.Api/Dockerfile
    container_name: minitwit-api
    depends_on:
      - db
    env_file:
      - .secrets
    ports:
      - "8080:8080"
      - "8081:8081"

  web:
    mem_limit: 256m
    build:
      context: ./src/minitwit.Web
      dockerfile: Dockerfile
    container_name: minitwit-web
    depends_on:
      - minitwit-api
    environment:
      - API_BASE_URL=http://minitwit-api:8080/
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "3000:3000"

volumes:
  db-data:
