global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'minitwit-api'
    static_configs:
      - targets: ['minitwit-api:8080']