{
 "title": "Work in progress dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP ms per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket{http_request_method=\"GET\", http_response_status_code=\"200\", http_route=\"api/twit/feed\", le=\"+Inf\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_bucket{http_request_method=\"GET\", http_response_status_code=\"200\", http_route=\"api/twit/public\", le=\"+Inf\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_bucket{http_request_method=\"GET\", http_response_status_code=\"404\", le=\"+Inf\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_server_request_duration_seconds_bucket{http_request_method=\"GET\", http_response_status_code=\"401\", le=\"+Inf\", http_route=\"api/user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status code 200, 500 and 503 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"500\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP \"failures\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_sd_http_failures_total{instance=\"prometheus:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_active_requests{http_request_method=\"GET\", instance=\"minitwit-api:8080\", job=\"minitwit-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{http_request_method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}