global:
  scrape_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape your Minitwit application
  - job_name: 'minitwit-api'
    static_configs:
      - targets: ['']  # Adjust port if needed
