name: build_and_test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.*

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution (Including Tests)
        run: dotnet build --configuration Debug --no-restore

      - name: List Test Output (Debugging)
        run: ls -R tests/Integration/bin/Debug/net8.0

      - name: Run Tests
        run: dotnet test --configuration Debug --verbosity normal
