name: build_and_test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build_and_test_NET:
    runs-on: ubuntu-latest
    environment: local_appsettings
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.*
      - name: Restore dependencies .NET
        run: dotnet restore
      - name: Build .NET
        run: dotnet build src/minitwit.Api --no-restore
      - name: Test .NET
        run: dotnet test tests/Integration/Integration.csproj --verbosity normal -e ${{ secrets.SIM_API_KEY }} -e ${{ env.TOKEN__KEY }} -e ${{ env.TOKEN__ISSUER }} -e ${{ env.TOKEN__AUDIENCE }} -e ${{ env.CONNECTIONSTRINGS_DEFAULTCONNECTION }}