name: build_and_test
on: 
  workflow_dispatch:
  workflow_call: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0

  kicks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Scan Iac with kics
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.6
        with:
          path: 'docker-compose.yaml,src/minitwit.Api/Dockerfile,src/minitwit.Web/Dockerfile'
          # The degree of severity can be sat by the following line
          fail_on: high,medium
          exclude_queries: '693, 400, 250'
          output_path: kicksResults/
      # Display the results in json format
      - name: display kics results
        run: k
          cat kicksResults/results.json
    
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.*
    - name: Restore dependencies
      run: dotnet restore src/minitwit.Api
    - name: Build
      run: dotnet build src/minitwit.Api --no-restore
   # - name: Test
   #   run: dotnet test tests/minitwit.tests --no-build --verbosity normal