name: build_and_test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test_NET:
    runs-on: ubuntu-latest
    environment: local_appsettings
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.*
      - name: Restore dependencies .NET
        run: dotnet restore
      - name: Build .NET
        run: dotnet build src/minitwit.Api --no-restore
      - name: Test .NET
        env:
          SimApiAccess__Key: ${{ secrets.SIM_API_KEY }}
          Token__Key: ${{ env.TOKEN__KEY }} 
          Token__Issuer: ${{ env.TOKEN__ISSUER }}
          Token__Audience: ${{ env.TOKEN__AUDIENCE }}
          ConnectionStrings__DefaultConnection: ${{ env.CONNECTIONSTRINGS_DEFAULTCONNECTION }}
        run: dotnet test tests/Integration/Integration.csproj --verbosity normal