name: Docs to PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Actions triggers only if changes are made in the specified paths
    paths:
      - 'report/**.md'
      - 'report/images/**'

jobs:
  converttopdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure output dir is created
        run: mkdir -p report/build

      # The merging are performed in alphabetic order
      - name: Merge markdown files
        uses: docker://pandoc/latex:3.6.4
        with:
          args: "bash -c \"pandoc report/*.md -o report/build/BSc_group_f.md\""

      - name: Convert to PDF
        uses: docker://pandoc/latex:3.6.4
        with:
          args: "bash -c \"pandoc report/build/BSc_group_f.md -o report/build/BSc_group_f.pdf\""

      - name: Upload PDF as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSc_group_f
          path: report/build/BSc_group_f.pdf
