name: Docs to PDF

on:
  push:
    branches:
      - main
    # Actions triggers only if changes are made in the specified paths
    paths:
      - 'report/**.md'
      - 'report/images/**'

jobs:
  converttopdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@
      
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y Pandoc

      - name: Ensure output dir is created
        run: mkdir -p output

      # The merging are performed in alphabetic order
      - name: Merge markdown files
        uses: docker://pandoc/latex:3.6.4
        with:
          args: "report/*.md -o report/build/BSc_group_f.md"

      - name: Convert to PDF
        uses: docker://pandoc/latex:3.6.4
        with:
          args: "report/build/BSc_group_f.md -o report/build/BSc_group_f.pdf"

      - name: Upload PDF as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSc_group_f
          path: report/build/BSc_group_f.pdf
