name: Docs to PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Actions triggers only if changes are made in the specified paths
    paths:
      - 'report/**.md'
      - 'report/images/**'

jobs:
  converttopdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc and latex engine
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Ensure output dir is created
        run: mkdir -p report/build

      - name: Convert to PDF
        run: pandoc report.md -o build/BSc_group_f.pdf

      - name: Upload PDF as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSc_group_f
          path: report/build/BSc_group_f.pdf

      - name: Commit report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f report/build/BSc_group_f.pdf
          git commit -m "Updated PDF from CI"
          git push
