name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main, actualYmlFiles ]
    tags: ['v.*.*.*', 'V.*.*.*' ]

jobs:
  tests:
    uses: ./.github/workflows/build_and_test.yaml

  release:
    needs: [tests]
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: /home/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.*

      - name: Build and package .NET API
        run: |
          tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          cd "src/minitwit.Api"

          for release in linux-x64 osx-x64 win-x64
          do
            release_os="minitwit-${tag}-${release}"
            dotnet publish minitwit.Api.csproj \
              --framework net8.0 \
              --runtime "$release" \
              -c Release \
              -o "$release_os" \
              /p:PublishTrimmed=true \
              /p:PublishSingleFile=true

            7z a -tzip "${{ github.workspace }}/minitwit.Api/${release_os}.zip" "./${release_os}/*"
            rm -r "${release_os}"
          done
        shell: bash

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build web
        working-directory: src/minitwit.Web
        run: |
          npm ci
          npm run build --if-present

      - name: Debug Web Build
        working-directory: src/minitwit.Web
        run: |
          echo "Checking contents of the web build directory..."
          ls -al

      - name: Package web build
        working-directory: src/minitwit.Web
        run: |
          tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          7z a -tzip "${{ github.workspace }}/minitwit.Web/minitwit-web-${tag}.zip" "dist/*"
        shell: bash

      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0 || echo 'v0.0.0')" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/minitwit.Api/minitwit-*.zip
            ${{ github.workspace }}/minitwit.Web/minitwit-web-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
