name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: ['v.*.*.*', 'V.*.*.*' ]

permission:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/build_and_test.yaml

  release:
    needs: ["tests"]
    runs-on: ubuntu-latest
    env:
      DOTNET_ROOT: /home/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Build and package .NET API
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          cd "src/minitwit.Api"

          # Build for multiple runtimes
          for release in linux-x64 osx-x64 win-x64
          do
            release_os="minitwit-${tag}-${release}"
            dotnet publish minitwit.Api.csproj \
              --framework net7.0 \
              --runtime "$release" \
              -c Release \
              -o "$release_os" \
              /p:PublishTrimmed=true \
              /p:PublishSingleFile=true

            # Zip up the published folder
            7z a -tzip "${{ github.workspace }}/minitwit.Api/${release_os}.zip" "./${release_os}/*"
            rm -r "${release_os}"
          done

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build web
        run: |
          cd "src/minitwit.Web"
          npm ci
          npm run build --if-present

      - name: Package web build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          cd "src/minitwit.Web"
          # Archive whatever your final build output is (e.g., `dist` folder)
          7z a -tzip "${{ github.workspace }}/minitwit.Web/minitwit-web-${tag}.zip" "./dist/*"

      - name: Set Tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/minitwit.Api/minitwit-*.zip
            ${{ github.workspace }}/minitwit.Web/minitwit-web-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
